image: alpine

pages:
  script:
    - apk update && apk add doxygen graphviz ttf-freefont
    - doxygen doc/doxygen.conf
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - feature/add-gitlab-pages-support
